const Questions = [{
        name: 'DATE_SURGERY',
        type: 'DATE'
    }, {
        name: 'SUBSPECIALTY',
        type: 'RADIO',
        numOptions: 7,
    }, {
        name: 'SURGERY',
        type: 'TEXT',
    }, {
        name: 'BRIEFING',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'PREP_RATING',
        type: 'RADIO',
        numOptions: 5,
    }, {
        name: 'PREP_COMMENT',
        type: 'TEXT',
    }, {
        name: 'GUIDANCE',
        type: 'RADIO',
        numOptions: 4,
    }, {
        name: 'PERFORMANCE',
        type: 'RADIO',
        numOptions: 5,
    }, {
        name: 'COMPLEXITY',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'KNOWLEDGE',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'OP_PLAN',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'APPROACH',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'PLANES',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'HANDLING',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'BLEEDING',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'NEED',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'POSOTP_PLAN',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'COMMUNICATION',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'RESPONSIVENESS',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'RESPECT',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'TEACHING',
        type: 'RADIO',
        numOptions: 3,
    }, {
        name: 'MORE_OF',
        type: 'TEXT',
    }, {
        name: 'LESS_OF',
        type: 'TEXT',
    }, {
        name: 'GENERAL',
        type: 'TEXT',
    }
];

module.exports = Questions;
